Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
try:
    import shap 
except ModuleNotFoundError: 
    !pip3 install --quiet shap

import shap
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

data = load_iris()
X = data.data
y = data.target

X_train, X_test, Y_train, Y_test = train_test_split(X,y, test_size=0.2, random_state=0)
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

explainer = shap.KernelExplainer(knn.predict_proba, X_train)
shap_values = explainer.shap_values(X_test)
# Pour chaque exemple, on donne l'importance de chacun des descripteurs dans la dÃ©cision de classification
shap.summary_plot(shap_values[0], X_test,data.feature_names)
------------------

----- stderr -----
Using 120 background data samples could cause slower run times. Consider using shap.sample(data, K) or shap.kmeans(data, K) to summarize the background as K samples.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[7], line 22[0m
[1;32m     20[0m shap_values [38;5;241m=[39m explainer[38;5;241m.[39mshap_values(X_test)
[1;32m     21[0m [38;5;66;03m# Pour chaque exemple, on donne l'importance de chacun des descripteurs dans la dÃ©cision de classification[39;00m
[0;32m---> 22[0m [43mshap[49m[38;5;241;43m.[39;49m[43msummary_plot[49m[43m([49m[43mshap_values[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[43mX_test[49m[43m,[49m[43mdata[49m[38;5;241;43m.[39;49m[43mfeature_names[49m[43m)[49m

File [0;32m/usr/local/lib/python3.12/site-packages/shap/plots/_beeswarm.py:555[0m, in [0;36msummary_legacy[0;34m(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, plot_size, layered_violin_max_num_bins, class_names, class_inds, color_bar_label, cmap, show_values_in_legend, auto_size_plot, use_log_scale)[0m
[1;32m    552[0m         [38;5;28;01massert[39;00m [38;5;28;01mFalse[39;00m, shape_msg [38;5;241m+[39m [38;5;124m"[39m[38;5;124m Perhaps the extra column in the shap_values matrix is the [39m[38;5;124m"[39m \
[1;32m    553[0m                       [38;5;124m"[39m[38;5;124mconstant offset? Of so just pass shap_values[:,:-1].[39m[38;5;124m"[39m
[1;32m    554[0m     [38;5;28;01melse[39;00m:
[0;32m--> 555[0m         [38;5;28;01massert[39;00m num_features [38;5;241m==[39m features[38;5;241m.[39mshape[[38;5;241m1[39m], shape_msg
[1;32m    557[0m [38;5;28;01mif[39;00m feature_names [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    558[0m     feature_names [38;5;241m=[39m np[38;5;241m.[39marray([labels[[38;5;124m'[39m[38;5;124mFEATURE[39m[38;5;124m'[39m] [38;5;241m%[39m [38;5;28mstr[39m(i) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(num_features)])

[0;31mAssertionError[0m: The shape of the shap_values matrix does not match the shape of the provided data matrix.

