Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from mca import MCA
acm = MCA(row_labels=var_chiens.index, var_labels=var_chiens.columns)
acm.fit(var_chiens.values)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [24][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmca[39;00m [38;5;28;01mimport[39;00m MCA
[0;32m----> 2[0m acm [38;5;241m=[39m [43mMCA[49m[43m([49m[43mrow_labels[49m[38;5;241;43m=[39;49m[43mvar_chiens[49m[38;5;241;43m.[39;49m[43mindex[49m[43m,[49m[43m [49m[43mvar_labels[49m[38;5;241;43m=[39;49m[43mvar_chiens[49m[38;5;241;43m.[39;49m[43mcolumns[49m[43m)[49m
[1;32m      3[0m acm[38;5;241m.[39mfit(var_chiens[38;5;241m.[39mvalues)

[0;31mTypeError[0m: __init__() got an unexpected keyword argument 'row_labels'
TypeError: __init__() got an unexpected keyword argument 'row_labels'

