Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data = np.load('./classification.npy')
plt.figure(figsize=(6,6))
plt.scatter(data.T[0], data.T[1], c='b',  s = 20, linewidths=0)
frame = plt.gca()
frame.axes.get_xaxis().set_visible(False)
frame.axes.get_yaxis().set_visible(False)
plt.tight_layout()

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m data [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m./classification.npy[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m6[39m,[38;5;241m6[39m))
[1;32m      3[0m plt[38;5;241m.[39mscatter(data[38;5;241m.[39mT[[38;5;241m0[39m], data[38;5;241m.[39mT[[38;5;241m1[39m], c[38;5;241m=[39m[38;5;124m'[39m[38;5;124mb[39m[38;5;124m'[39m,  s [38;5;241m=[39m [38;5;241m20[39m, linewidths[38;5;241m=[39m[38;5;241m0[39m)

File [0;32m/usr/local/lib/python3.9/site-packages/numpy/lib/npyio.py:405[0m, in [0;36mload[0;34m(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)[0m
[1;32m    403[0m     own_fid [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    404[0m [38;5;28;01melse[39;00m:
[0;32m--> 405[0m     fid [38;5;241m=[39m stack[38;5;241m.[39menter_context([38;5;28;43mopen[39;49m[43m([49m[43mos_fspath[49m[43m([49m[43mfile[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[1;32m    406[0m     own_fid [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    408[0m [38;5;66;03m# Code to distinguish from NumPy binary files and pickles.[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './classification.npy'
FileNotFoundError: [Errno 2] No such file or directory: './classification.npy'

