Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Utilisation d'un sous-ensemble de Xmnist (pour ne pas surcharger la visualisation)
ymnist=ymnist.astype(int)
nb_digits = 10000
s = np.arange(Xmnist.shape[0])
np.random.shuffle(s)
X0=Xmnist[s]
y0=ymnist[s]
Xdata = X0[:nb_digits]
ydata = y0[:nb_digits]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Input [0;32mIn [8][0m, in [0;36m<module>[0;34m[0m
[1;32m      4[0m s [38;5;241m=[39m np[38;5;241m.[39marange(Xmnist[38;5;241m.[39mshape[[38;5;241m0[39m])
[1;32m      5[0m np[38;5;241m.[39mrandom[38;5;241m.[39mshuffle(s)
[0;32m----> 6[0m X0[38;5;241m=[39m[43mXmnist[49m[43m[[49m[43ms[49m[43m][49m
[1;32m      7[0m y0[38;5;241m=[39mymnist[s]
[1;32m      8[0m Xdata [38;5;241m=[39m X0[:nb_digits]

File [0;32m/usr/local/lib/python3.9/site-packages/pandas/core/frame.py:3813[0m, in [0;36mDataFrame.__getitem__[0;34m(self, key)[0m
[1;32m   3811[0m     [38;5;28;01mif[39;00m is_iterator(key):
[1;32m   3812[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[0;32m-> 3813[0m     indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mcolumns[39;49m[38;5;124;43m"[39;49m[43m)[49m[[38;5;241m1[39m]
[1;32m   3815[0m [38;5;66;03m# take() does not accept boolean indexers[39;00m
[1;32m   3816[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(indexer, [38;5;124m"[39m[38;5;124mdtype[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m) [38;5;241m==[39m [38;5;28mbool[39m:

File [0;32m/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py:6070[0m, in [0;36mIndex._get_indexer_strict[0;34m(self, key, axis_name)[0m
[1;32m   6067[0m [38;5;28;01melse[39;00m:
[1;32m   6068[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[0;32m-> 6070[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[1;32m   6072[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[1;32m   6073[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[1;32m   6074[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [0;32m/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py:6130[0m, in [0;36mIndex._raise_if_missing[0;34m(self, key, indexer, axis_name)[0m
[1;32m   6128[0m     [38;5;28;01mif[39;00m use_interval_msg:
[1;32m   6129[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[0;32m-> 6130[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[1;32m   6132[0m not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[1;32m   6133[0m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[0;31mKeyError[0m: "None of [Int64Index([ 2560,  1973, 26440, 14739, 66130, 60072, 28840, 25866,  8762,\n             7891,\n            ...\n            10887, 33553, 58606,  2414, 28848, 44413,  8116, 12218,  1716,\n             8804],\n           dtype='int64', length=70000)] are in the [columns]"
KeyError: "None of [Int64Index([ 2560,  1973, 26440, 14739, 66130, 60072, 28840, 25866,  8762,\n             7891,\n            ...\n            10887, 33553, 58606,  2414, 28848, 44413,  8116, 12218,  1716,\n             8804],\n           dtype='int64', length=70000)] are in the [columns]"

